// WARNING: this file is auto generated, any changes will be lost
import { createDesignComponent, CanvasStore } from "framer"
const canvas = CanvasStore.shared(); // CANVAS_DATA;
export const AddMetaScrollComponent = createDesignComponent<{parentSize?:{width:number|string,height:number|string},width?:number|string,height?:number|string}>(canvas, "id_fO8AKBExU", {}, 375,535);
export const AreaTitleComponent = createDesignComponent<{parentSize?:{width:number|string,height:number|string},width?:number|string,height?:number|string}>(canvas, "id_cRarAK9F0", {}, 371,38);
export const BtnSendDeeplink = createDesignComponent<{parentSize?:{width:number|string,height:number|string},width?:number|string,height?:number|string}>(canvas, "id_AkRJW5PpG", {}, 239,36);
export const BtnSmall = createDesignComponent<{parentSize?:{width:number|string,height:number|string},width?:number|string,height?:number|string}>(canvas, "id_WR_TCQZEA", {}, 93,40);
export const Btns = createDesignComponent<{parentSize?:{width:number|string,height:number|string},width?:number|string,height?:number|string}>(canvas, "id_prBD79aJm", {}, 375,45);
export const CancelBtn = createDesignComponent<{parentSize?:{width:number|string,height:number|string},width?:number|string,height?:number|string}>(canvas, "id_bpM5Brxxf", {}, 44,44);
export const CheckBtn = createDesignComponent<{parentSize?:{width:number|string,height:number|string},width?:number|string,height?:number|string}>(canvas, "id_JvFMmE1DD", {}, 44,44);
export const DarkBottomNav = createDesignComponent<{parentSize?:{width:number|string,height:number|string},width?:number|string,height?:number|string}>(canvas, "id_K5exQQIMw", {}, 375,56);
export const ExampleTag = createDesignComponent<{parentSize?:{width:number|string,height:number|string},width?:number|string,height?:number|string}>(canvas, "id_yP5fxkNnk", {}, 136,32);
export const Gauge979ca6LightComponent = createDesignComponent<{parentSize?:{width:number|string,height:number|string},width?:number|string,height?:number|string}>(canvas, "id_lKEhswZvU", {}, 369,368);
export const LinkTypeArea = createDesignComponent<{parentSize?:{width:number|string,height:number|string},width?:number|string,height?:number|string}>(canvas, "id_Rd2MoD_gI", {}, 375,133);
export const LinkTypeBtnSelfDefined = createDesignComponent<{parentSize?:{width:number|string,height:number|string},width?:number|string,height?:number|string}>(canvas, "id_OZzwFRyaC", {}, 160,34);
export const ListElement_Component = createDesignComponent<{parentSize?:{width:number|string,height:number|string},width?:number|string,height?:number|string}>(canvas, "id_AFMNmClMZ", {}, 375,139);
export const NameOfBtn = createDesignComponent<{parentSize?:{width:number|string,height:number|string},width?:number|string,height?:number|string}>(canvas, "id_z1wquiqmT", {}, 307,66);
export const PageIndicatorComponent = createDesignComponent<{parentSize?:{width:number|string,height:number|string},width?:number|string,height?:number|string}>(canvas, "id_oAhpxtxDV", {}, 265,38);
export const PageIndicatorSmallComponent = createDesignComponent<{parentSize?:{width:number|string,height:number|string},width?:number|string,height?:number|string}>(canvas, "id_v7zUumnTf", {}, 160,32);
export const PageIndicatorSmallComponent_1 = createDesignComponent<{parentSize?:{width:number|string,height:number|string},width?:number|string,height?:number|string}>(canvas, "id_cmhNGITDV", {}, 171,32);
export const PreviewDummy = createDesignComponent<{parentSize?:{width:number|string,height:number|string},width?:number|string,height?:number|string}>(canvas, "id_v0lW3fANA", {}, 87,87);
export const Privacy = createDesignComponent<{parentSize?:{width:number|string,height:number|string},width?:number|string,height?:number|string}>(canvas, "id_De025W8_U", {}, 375,133);
export const Screen_Nav2 = createDesignComponent<{parentSize?:{width:number|string,height:number|string},width?:number|string,height?:number|string}>(canvas, "id_GcgE268tF", {}, 375,56);
export const SearchControlStack = createDesignComponent<{parentSize?:{width:number|string,height:number|string},width?:number|string,height?:number|string}>(canvas, "id_V4GxMBY1A", {}, 374,48);
export const SearchWindowComponent = createDesignComponent<{parentSize?:{width:number|string,height:number|string},width?:number|string,height?:number|string}>(canvas, "id_lvkYMUijW", {}, 375,64);
export const StatusbarDiversus = createDesignComponent<{parentSize?:{width:number|string,height:number|string},width?:number|string,height?:number|string}>(canvas, "id_XEJDPbjnH", {}, 375,20);
export const TC_Indicator = createDesignComponent<{parentSize?:{width:number|string,height:number|string},width?:number|string,height?:number|string}>(canvas, "id_RR_Q9nQtj", {}, 103,32);
export const Title = createDesignComponent<{parentSize?:{width:number|string,height:number|string},width?:number|string,height?:number|string}>(canvas, "id_vMM_xJfry", {}, 375,112);
export const TriangleBGComponent = createDesignComponent<{parentSize?:{width:number|string,height:number|string},width?:number|string,height?:number|string}>(canvas, "id_D9ub0bw4p", {}, 375,667);
